spring:
  datasource:
    url: jdbc:postgresql://${DOTENV_DB_HOST}/${DOTENV_DB_NAME}
    username: ${DOTENV_DB_USER}
    password: ${DOTENV_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        # dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
